### ISSUE TITLE
Prism에서 rest 오류가 나는 건에 대해서

### ISSUE THREAD

**Issue by Jungwoo-Son** [snippet-io/Frontend#24]
해결 하기 위해서는 language.js의 1번 라인을 `import "prismjs/components/prism-core"`로 변경해야 합니다.

prismjs/components/prism-javascript와 같은 모듈들은 하이라이팅에 사용할 수 있는 언어 종류를 추가해줍니다.
이의 구현은 전역 객체인 Prsim의 프로퍼티인 languages 객체에 언어에 대한 프로퍼티를 추가해주는 것으로 구현됩니다.
`Prism.languages.javascript = ~~~`

위의 동작을 위해 Prism라이브러리에서 전역 객체인 Prism을 만들어주는데 이러한 동작을 하는 모듈이 2개 있습니다.
`prism`과 `prism/components/prism-core`입니다.

현재 languages.js에서는 `prism` 모듈이 사용되고 있으나 다른 Editor와 관련된 코드들은 `prism/components/prism-core`를 사용하고 있습니다.

이는 languages.js에서 전역 객체 Prism에다가 언어를 추가하더라도 `prism/components/prism-core`를 import할 때 전역 객체 Prism이 다시 초기화 되도록 만듭니다.

따라서 두 모듈 중 하나만 사용해야하는데 `prism` 모듈은 몇몇 언어들이 이미 추가된 상태이고 `prism/components/prism-core`은 그와 반대로 어떠한 언어도 추가되지 않은 깨끗한 상태입니다.

저는 명시적으로 언어를 추가하기 위해  `prism/components/prism-core`를 추천합니다.
이와 관련된 변경사항을 풀리퀘 날리겠습니다.

**Comment by heunyam** [comment]
좋다
